#
# Makefile for sunxi specific clk
#

obj-y += clk-factors.o clk-periph.o
obj-${CONFIG_COMMON_CLK_DEBUG} += clk-debugfs.o
obj-${CONFIG_ARCH_SUN8IW10} += clk-sun8iw10.o
obj-${CONFIG_ARCH_SUN8IW11} += clk-sun8iw11.o
obj-${CONFIG_ARCH_SUN50IW1} += clk-sun50iw1.o
obj-${CONFIG_ARCH_SUN50IW2} += clk-sun50iw2.o
obj-${CONFIG_ARCH_SUN50IW3} += clk-sun50iw3.o
obj-${CONFIG_ARCH_SUN50IW6} += clk-sun50iw6.o
